// Generado por npm run tokens desde tokens/tokens.json. No editar a mano.
// Valores resueltos para la ficha técnica en PDF (src/pdf/): Color Light,
// Dimension Desktop y Type Mobile. Dimensiones en px (número).

export const PRINT_TOKENS = Object.freeze({
  "space/section/2xs": 32,
  "space/section/xs": 48,
  "space/section/sm": 64,
  "space/section/md": 96,
  "space/section/lg": 128,
  "space/section/xl": 160,
  "space/gap/xs": 4,
  "space/gap/sm": 8,
  "space/gap/sm-md": 12,
  "space/gap/md": 16,
  "space/gap/lg": 24,
  "space/gap/xl": 32,
  "space/gap/xl-2xl": 40,
  "space/gap/2xl": 48,
  "space/gap/3xl": 64,
  "space/gap/4xl": 80,
  "space/gap/5xl": 96,
  "space/gap/6xl": 128,
  "space/padding/2xs": 3,
  "space/padding/xs": 4,
  "space/padding/sm": 8,
  "space/padding/sm-md": 12,
  "space/padding/md": 16,
  "space/padding/lg": 24,
  "space/padding/xl": 32,
  "space/padding/xl-2xl": 40,
  "space/padding/2xl": 48,
  "space/padding/3xl": 64,
  "space/padding/4xl": 80,
  "space/padding/5xl": 96,
  "space/padding/6xl": 128,
  "font/family/sans": "Albert Sans",
  "border/default": 1,
  "border/focus": 1,
  "border/strong": 2,
  "color/bg/default": "#FFFFFF",
  "color/bg/subtle": "#F0F0F0",
  "color/bg/inverse": "#101010",
  "color/surface/default": "#FFFFFF",
  "color/surface/faint": "#FBFBFB",
  "color/surface/hover": "#F7F7F7",
  "color/surface/soft": "#F4F4F4",
  "color/surface/subtle": "#F0F0F0",
  "color/surface/selected": "#E9E9E9",
  "color/surface/strong": "#E0E0E0",
  "color/surface/inverse": "#101010",
  "color/surface/inverse-hover": "#2E2E2E",
  "color/surface/inverse-pressed": "#666666",
  "color/surface/transparent": "#00000000",
  "color/text/primary": "#101010",
  "color/text/secondary": "#2E2E2E",
  "color/text/tertiary": "#666666",
  "color/text/inverse": "#FFFFFF",
  "color/text/accent": "#101010",
  "color/text/disabled": "#ADADAD",
  "color/text/error": "#A8322A",
  "color/text/success": "#3F6F53",
  "color/text/warning": "#8A5F10",
  "color/icon/primary": "#101010",
  "color/icon/secondary": "#2E2E2E",
  "color/icon/tertiary": "#666666",
  "color/icon/accent": "#101010",
  "color/icon/inverse": "#FFFFFF",
  "color/icon/disabled": "#ADADAD",
  "color/border/subtle": "#1010101A",
  "color/border/default": "#10101038",
  "color/border/hover": "#8A8A8A",
  "color/border/strong": "#101010",
  "color/border/disabled": "#E0E0E0",
  "color/border/focus": "#101010",
  "color/border/error": "#A8322A",
  "color/action/primary": "#101010",
  "color/action/primary-hover": "#2E2E2E",
  "color/action/on-primary": "#FFFFFF",
  "color/accent/default": "#101010",
  "color/overlay/scrim": "#00000099",
  "color/overlay/translucent": "#1010101A",
  "layout/gutter": 40,
  "layout/card-min": 280,
  "layout/card-min-wide": 340,
  "layout/compare-media-max": 2000,
  "layout/measure": 400,
  "layout/measure-wide": 520,
  "layout/gallery-thumb": 105,
  "layout/filter-panel": 560,
  "layout/table-thumb": 56,
  "layout/compare-thumb": 48,
  "layout/compare-thumb-sm": 28,
  "layout/compare-slot": 400,
  "layout/compare-label": 200,
  "layout/compare-column": 160,
  "layout/mega-menu-image": 438,
  "layout/search-field": 360,
  "layout/search-thumb": 48,
  "layout/max-width": 1792,
  "layout/select-filter": 160,
  "layout/select-menu-filter": 200,
  "layout/footer-column": 200,
  "layout/footer-tagline": 240,
  "layout/featured-thumb": 160,
  "layout/pdf-spec-label": 260,
  "type/display/size": 40,
  "type/display/leading": 44,
  "type/display-sm/size": 32,
  "type/display-sm/leading": 40,
  "type/heading-1/size": 32,
  "type/heading-1/leading": 40,
  "type/heading-2/size": 24,
  "type/heading-2/leading": 32,
  "type/heading-3/size": 20,
  "type/heading-3/leading": 28,
  "type/body-xl/size": 16,
  "type/body-xl/leading": 24,
  "type/body-lg/size": 16,
  "type/body-lg/leading": 24,
  "type/body/size": 16,
  "type/body/leading": 24,
  "type/body-sm/size": 12,
  "type/body-sm/leading": 16,
  "type/label/size": 12,
  "type/label/leading": 16,
  "type/label-sm/size": 10,
  "type/label-sm/leading": 14,
  "type/caption/size": 12,
  "type/caption/leading": 14
});

export const PRINT_ROLES = Object.freeze({
  "display": {
    "fontFamily": "Albert Sans",
    "fontWeight": 300,
    "fontSize": 40,
    "lineHeight": 44,
    "letterSpacing": -0.8
  },
  "display-sm": {
    "fontFamily": "Albert Sans",
    "fontWeight": 300,
    "fontSize": 32,
    "lineHeight": 40,
    "letterSpacing": -0.4
  },
  "heading-1": {
    "fontFamily": "Albert Sans",
    "fontWeight": 300,
    "fontSize": 32,
    "lineHeight": 40,
    "letterSpacing": -0.4
  },
  "heading-2": {
    "fontFamily": "Albert Sans",
    "fontWeight": 300,
    "fontSize": 24,
    "lineHeight": 32,
    "letterSpacing": 0
  },
  "heading-3": {
    "fontFamily": "Albert Sans",
    "fontWeight": 400,
    "fontSize": 20,
    "lineHeight": 28,
    "letterSpacing": 0
  },
  "body-xl": {
    "fontFamily": "Albert Sans",
    "fontWeight": 400,
    "fontSize": 16,
    "lineHeight": 24,
    "letterSpacing": 0
  },
  "body-lg": {
    "fontFamily": "Albert Sans",
    "fontWeight": 300,
    "fontSize": 16,
    "lineHeight": 24,
    "letterSpacing": 0
  },
  "body-lg-regular": {
    "fontFamily": "Albert Sans",
    "fontWeight": 400,
    "fontSize": 16,
    "lineHeight": 24,
    "letterSpacing": 0
  },
  "body-lg-medium": {
    "fontFamily": "Albert Sans",
    "fontWeight": 500,
    "fontSize": 16,
    "lineHeight": 24,
    "letterSpacing": 0
  },
  "body": {
    "fontFamily": "Albert Sans",
    "fontWeight": 300,
    "fontSize": 16,
    "lineHeight": 24,
    "letterSpacing": 0
  },
  "body-regular": {
    "fontFamily": "Albert Sans",
    "fontWeight": 400,
    "fontSize": 16,
    "lineHeight": 24,
    "letterSpacing": 0
  },
  "body-medium": {
    "fontFamily": "Albert Sans",
    "fontWeight": 500,
    "fontSize": 16,
    "lineHeight": 24,
    "letterSpacing": 0
  },
  "body-strong": {
    "fontFamily": "Albert Sans",
    "fontWeight": 600,
    "fontSize": 16,
    "lineHeight": 24,
    "letterSpacing": 0
  },
  "body-sm": {
    "fontFamily": "Albert Sans",
    "fontWeight": 400,
    "fontSize": 12,
    "lineHeight": 16,
    "letterSpacing": 0
  },
  "body-sm-medium": {
    "fontFamily": "Albert Sans",
    "fontWeight": 500,
    "fontSize": 12,
    "lineHeight": 16,
    "letterSpacing": 0
  },
  "label": {
    "fontFamily": "Albert Sans",
    "fontWeight": 400,
    "fontSize": 12,
    "lineHeight": 16,
    "letterSpacing": 1,
    "textTransform": "uppercase"
  },
  "label-sm": {
    "fontFamily": "Albert Sans",
    "fontWeight": 500,
    "fontSize": 10,
    "lineHeight": 14,
    "letterSpacing": 1,
    "textTransform": "uppercase"
  },
  "caption": {
    "fontFamily": "Albert Sans",
    "fontWeight": 400,
    "fontSize": 12,
    "lineHeight": 14,
    "letterSpacing": 0.4
  },
  "caption-medium": {
    "fontFamily": "Albert Sans",
    "fontWeight": 500,
    "fontSize": 12,
    "lineHeight": 14,
    "letterSpacing": 0.4
  }
});
